name = "roll-dorado-bonus-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-bonus.com.pt"
HMAC_KEY = "aa27da173a14d366fcd5cfb73c4bd8527f36f0b404229f7f6f61bacc7138ab40"
COOKIE_NAME = "wj8"
PLAY_PATH = "begin"
BUTTON_ID = "p24883fa89b7aa85f51f2fe390c5abb8b"
GATE_SALT = "269f608f6c0a2810"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "omt4"
CTA_SELECTOR = ".play-button"
